seed_everything: true
per_run_seed: true
tags:
  exp: &exp pixdit_promoe_xl_imagenet256
torch_hub_dir: null
huggingface_cache_dir: null
auto_resume: false
trainer:
  default_root_dir: ./train_logs/
  accelerator: gpu
  strategy: ddp
  devices: 4
  num_nodes: 1
  precision: bf16-mixed
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  accumulate_grad_batches: 64
  logger: false
  num_sanity_val_steps: 0
  max_steps: 500000
  val_check_interval: null
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  inference_mode: true
  use_distributed_sampler: false
  callbacks:
    - class_path: src.utils.CheckpointHook
      init_args:
        every_n_epochs: 1
        save_on_train_epoch_end: true
        save_top_k: 0
        save_last: true
    - class_path: src.utils.SaveImagesHook
      init_args:
        save_dir: val_256_promoe_xl
        save_compressed: true
model:
  enable_profiling: true
  profiling_print_freq: 1000
  profiling_warmup_steps: 100
  num_classes: 1000
  denoiser:
    class_path: pixdit_core.pixeldit_c2i.PixDiTProMoE
    init_args:
      in_channels: 3
      patch_size: 16
      num_groups: 16
      hidden_size: 1152
      patch_depth: 28
      pixel_depth: 4
      num_classes: 1000
      pixel_hidden_size: 16
      num_routed_experts: 12
      expert_intermediate_size: 2304
      rcl_temperature: 0.07
      rcl_weight: 1.0
  diffusion_trainer:
    class_path: src.diffusion.ProMoEFlowTrainer
    init_args:
      lognorm_t: true
      timeshift: 1.0
      null_condition_p: 0.1
      scheduler: &scheduler src.diffusion.LinearScheduler
  diffusion_sampler:
    class_path: src.diffusion.FlowDPMSolverSampler
    init_args:
      num_steps: 100
      guidance: 3.25
      timeshift: 1.0
      guidance_interval_min: 0.1
      guidance_interval_max: 1.0
      scheduler: *scheduler
      w_scheduler: src.diffusion.LinearScheduler
      guidance_fn: src.diffusion.simple_guidance_fn
      step_fn: src.diffusion.ode_step_fn
  ema_tracker:
    class_path: src.utils.SimpleEMA
    init_args:
      decay: 0.9999
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-4
      weight_decay: 0.0
data:
  train_dataset:
    class_path: src.data.CustomINH5Dataset
    init_args:
      data_dir: ImageNet-1k/imagenet256_h5
  eval_dataset:
    class_path: src.data.ClassLabelRandomNDataset
    init_args:
      num_classes: 1000
      conditions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
      max_num_instances: 100
      latent_shape: [3, 256, 256]
  pred_dataset:
    class_path: src.data.ClassLabelRandomNDataset
    init_args:
      num_classes: 1000
      max_num_instances: 50000
      latent_shape: [3, 256, 256]
  train_batch_size: 1
  train_num_workers: 4
  eval_batch_size: 100
  pred_batch_size: 1
  pred_num_workers: 1
